import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SARAH_V1_CONTEXT } from "../src/fixtures/sarah-v1";
import {
  FINANCIAL_CONTEXT_PERSISTENCE_SCHEMA,
  financialContextToPersistence
} from "../src/infrastructure/persistence/financial-context-persistence";

const SARAH_USER_ID = "11111111-1111-4111-8111-111111111111";
const ALEX_USER_ID = "22222222-2222-4222-8222-222222222222";
const ONBOARDING_USER_ID = "33333333-3333-4333-8333-333333333333";
const VISUAL_ONBOARDING_USER_ID = "88888888-8888-4888-8888-888888888888";

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function authUser(input: Readonly<{
  id: string;
  identityId: string;
  email: string;
  password: string;
  displayName: string;
}>): string {
  const appMetadata = JSON.stringify({
    provider: "email",
    providers: ["email"],
    future_you_fixture: true
  });
  const userMetadata = JSON.stringify({ display_name: input.displayName });
  const identityData = JSON.stringify({
    sub: input.id,
    email: input.email,
    email_verified: true,
    phone_verified: false
  });
  return `insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  confirmation_token, recovery_token, email_change_token_new, email_change_token_current,
  email_change, reauthentication_token, raw_app_meta_data, raw_user_meta_data,
  is_super_admin, created_at, updated_at, is_sso_user, is_anonymous
) values (
  '00000000-0000-0000-0000-000000000000',
  ${sqlString(input.id)},
  'authenticated',
  'authenticated',
  ${sqlString(input.email)},
  extensions.crypt(${sqlString(input.password)}, extensions.gen_salt('bf')),
  statement_timestamp(), '', '', '', '', '', '',
  ${sqlString(appMetadata)}::jsonb,
  ${sqlString(userMetadata)}::jsonb,
  false, statement_timestamp(), statement_timestamp(), false, false
);

insert into auth.identities (
  id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) values (
  ${sqlString(input.identityId)},
  ${sqlString(input.email)},
  ${sqlString(input.id)},
  ${sqlString(identityData)}::jsonb,
  'email', statement_timestamp(), statement_timestamp(), statement_timestamp()
);`;
}

export function createSupabaseSeed(): string {
  const contextPayload = JSON.stringify(financialContextToPersistence(SARAH_V1_CONTEXT));
  return `-- GENERATED by scripts/generate-supabase-seed.ts. Do not hand-edit.
-- Local-only credentials are deterministic so browser and API isolation tests are reproducible.

select set_config('app.future_you_seed', 'enabled', false);

${authUser({
  id: SARAH_USER_ID,
  identityId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  email: "sarah@example.test",
  password: "Sarah-Local-Only-2026!",
  displayName: "Sarah Wonk"
})}

${authUser({
  id: ALEX_USER_ID,
  identityId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
  email: "alex@example.test",
  password: "Alex-Local-Only-2026!",
  displayName: "Alex Morgan"
})}

${authUser({
  id: ONBOARDING_USER_ID,
  identityId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
  email: "onboarding@example.test",
  password: "Onboarding-Local-Only-2026!",
  displayName: "Manual Onboarding User"
})}

${authUser({
  id: VISUAL_ONBOARDING_USER_ID,
  identityId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  email: "visual-onboarding@example.test",
  password: "Visual-Onboarding-Only-2026!",
  displayName: "Visual Onboarding User"
})}

insert into public.financial_context_versions (
  user_id, version_id, context_id, predecessor_version_id, domain_schema_version,
  persistence_schema_version, payload, source, origin, confirmation_reason
) values (
  ${sqlString(SARAH_USER_ID)},
  ${sqlString(SARAH_V1_CONTEXT.version)},
  ${sqlString(SARAH_V1_CONTEXT.id)},
  null,
  ${sqlString(SARAH_V1_CONTEXT.schemaVersion)},
  ${sqlString(FINANCIAL_CONTEXT_PERSISTENCE_SCHEMA)},
  ${sqlString(contextPayload)}::jsonb,
  'canonical Sarah v1 code fixture',
  'fixture',
  'Slice 3 deterministic local demo seed'
);

update public.profiles
set current_financial_context_version_id = ${sqlString(SARAH_V1_CONTEXT.version)},
    onboarding_state = 'ready',
    is_demo = true,
    updated_at = statement_timestamp()
where user_id = ${sqlString(SARAH_USER_ID)};

insert into private.employers (
  employer_id, public_company_id, display_name, status
) values (
  '44444444-4444-4444-8444-444444444444',
  'FY7K3M9Q2D',
  'OniBank',
  'ACTIVE'
);

insert into private.employee_provisions (
  provision_id, employer_id, work_email_normalized, work_email_fingerprint,
  external_reference, status, available_from, expires_at
) values (
  '55555555-5555-4555-8555-555555555555',
  '44444444-4444-4444-8444-444444444444',
  'newstarter@onibank.example.test',
  encode(extensions.digest(convert_to('local-seed:newstarter@onibank.example.test', 'UTF8'), 'sha256'), 'hex'),
  'local-browser-acceptance',
  'ELIGIBLE',
  statement_timestamp(),
  statement_timestamp() + interval '30 days'
), (
  '55555555-5555-4555-8555-555555555556',
  '44444444-4444-4444-8444-444444444444',
  'integration@onibank.example.test',
  encode(extensions.digest(convert_to('local-seed:integration@onibank.example.test', 'UTF8'), 'sha256'), 'hex'),
  'local-integration-acceptance',
  'ELIGIBLE',
  statement_timestamp(),
  statement_timestamp() + interval '30 days'
), (
  '55555555-5555-4555-8555-555555555557',
  '44444444-4444-4444-8444-444444444444',
  'concurrent@onibank.example.test',
  encode(extensions.digest(convert_to('local-seed:concurrent@onibank.example.test', 'UTF8'), 'sha256'), 'hex'),
  'local-concurrency-acceptance',
  'ELIGIBLE',
  statement_timestamp(),
  statement_timestamp() + interval '30 days'
), (
  '55555555-5555-4555-8555-555555555558',
  '44444444-4444-4444-8444-444444444444',
  'collision@onibank.example.test',
  encode(extensions.digest(convert_to('local-seed:collision@onibank.example.test', 'UTF8'), 'sha256'), 'hex'),
  'local-existing-account-acceptance',
  'ELIGIBLE',
  statement_timestamp(),
  statement_timestamp() + interval '30 days'
);
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(
    fileURLToPath(new URL("../supabase/seed.sql", import.meta.url)),
    createSupabaseSeed(),
    { encoding: "utf8" }
  );
}
