import { z } from "zod";
import type { ConversationInterpretation } from "./contracts";
import {
  AMBIGUITY_IDS,
  EXPLANATION_TARGET_IDS,
  INTERPRETATION_INTENT_IDS,
  SCENARIO_FOLLOW_UP_IDS,
  SCENARIO_REFERENCE_STRATEGY_IDS,
  SCENARIO_SELECTION_TARGET_IDS,
  UNSUPPORTED_CATEGORY_IDS
} from "./interpretation-policy";
import {
  completeTimingInterpretationSchema as activeCompleteTimingInterpretationSchema
} from "./timing-policy";

export const conversationIntentKindSchema = z.enum(INTERPRETATION_INTENT_IDS);

export const amountInterpretationSchema = z.object({
  quote: z.string().min(1).max(80),
  currency: z.enum(["GBP", "UNSUPPORTED"])
}).strict();

export const legacyTimingInterpretationSchema = z.object({
  quote: z.string().max(120).nullable(),
  kind: z.enum([
    "NEXT_MONTH",
    "MONTHS_AFTER_SELECTED",
    "NAMED_MONTH",
    "EXPLICIT_YEAR_MONTH",
    "MISSING",
    "AMBIGUOUS"
  ]),
  monthNumber: z.number().int().min(1).max(12).nullable(),
  year: z.number().int().min(2000).max(2200).nullable(),
  offsetMonths: z.number().int().min(0).max(120).nullable()
}).strict();

/** Frozen C1D/v2 runtime contract retained for historical comparison. */
export const completeTimingInterpretationSchemaV2 = z.object({
  quote: z.string().min(1).max(120),
  kind: z.enum(["NEXT_MONTH", "MONTHS_AFTER_SELECTED", "NAMED_MONTH", "EXPLICIT_YEAR_MONTH"]),
  monthNumber: z.number().int().min(1).max(12).nullable(),
  year: z.number().int().min(2000).max(2200).nullable(),
  offsetMonths: z.number().int().min(0).max(120).nullable()
}).strict().superRefine((value, context) => {
  if (value.kind === "NEXT_MONTH" && (value.monthNumber !== null || value.year !== null || value.offsetMonths !== 1)) {
    context.addIssue({ code: "custom", message: "NEXT_MONTH requires only offsetMonths=1." });
  }
  if (value.kind === "MONTHS_AFTER_SELECTED" && (value.monthNumber !== null || value.year !== null || value.offsetMonths === null || value.offsetMonths < 1)) {
    context.addIssue({ code: "custom", message: "MONTHS_AFTER_SELECTED requires a positive offset only." });
  }
  if (value.kind === "NAMED_MONTH" && (value.monthNumber === null || value.year !== null || value.offsetMonths !== null)) {
    context.addIssue({ code: "custom", message: "NAMED_MONTH requires only monthNumber." });
  }
  if (value.kind === "EXPLICIT_YEAR_MONTH" && (value.monthNumber === null || value.year === null || value.offsetMonths !== null)) {
    context.addIssue({ code: "custom", message: "EXPLICIT_YEAR_MONTH requires year and monthNumber only." });
  }
});

/** Active v3 contract, generated by the canonical timing-policy module. */
export const completeTimingInterpretationSchema = activeCompleteTimingInterpretationSchema;

export const pendingClarificationSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("PURCHASE_AMOUNT"),
    originalMessageId: z.string().min(3).max(160),
    partialPurpose: z.string().max(160).nullable(),
    partialTiming: legacyTimingInterpretationSchema,
    attemptedOperation: z.enum(["CREATE_ONE_OFF_PURCHASE", "CHANGE_PURCHASE_AMOUNT"]).optional()
  }).strict(),
  z.object({
    type: z.literal("PURCHASE_MONTH"),
    originalMessageId: z.string().min(3).max(160),
    amountQuote: z.string().min(1).max(80),
    partialPurpose: z.string().max(160).nullable(),
    attemptedOperation: z.enum(["CREATE_ONE_OFF_PURCHASE", "CHANGE_PURCHASE_MONTH"]).optional()
  }).strict(),
  z.object({
    type: z.literal("SCENARIO_REFERENCE"),
    originalMessageId: z.string().min(3).max(160),
    availableRunIds: z.array(z.string().min(3).max(160)).max(30),
    attemptedOperation: z.enum(SCENARIO_FOLLOW_UP_IDS).optional(),
    amount: amountInterpretationSchema.optional(),
    amountMinorUnits: z.string().regex(/^(?:0|[1-9]\d*)$/).optional(),
    timing: completeTimingInterpretationSchema.optional(),
    explanationTarget: z.enum(EXPLANATION_TARGET_IDS).optional(),
    goalReferenceQuote: z.string().max(160).nullable().optional()
  }).strict()
]);

function buildConversationInterpretationSchema(timingSchema: z.ZodTypeAny) {
  return z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("CREATE_ONE_OFF_PURCHASE"),
    amount: amountInterpretationSchema,
    timing: timingSchema,
    purposeQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("CHANGE_PURCHASE_AMOUNT"),
    amount: amountInterpretationSchema,
    scenarioReferenceStrategy: z.enum(SCENARIO_REFERENCE_STRATEGY_IDS),
    scenarioReferenceQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("CHANGE_PURCHASE_MONTH"),
    timing: timingSchema,
    scenarioReferenceStrategy: z.enum(SCENARIO_REFERENCE_STRATEGY_IDS),
    scenarioReferenceQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("EXPLAIN_SELECTED_RESULT"),
    explanationTarget: z.enum(EXPLANATION_TARGET_IDS),
    goalReferenceQuote: z.string().max(160).nullable(),
    scenarioReferenceStrategy: z.enum(SCENARIO_REFERENCE_STRATEGY_IDS),
    scenarioReferenceQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("SELECT_EXISTING_SCENARIO"),
    selectionTarget: z.enum(SCENARIO_SELECTION_TARGET_IDS),
    scenarioLabelQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("CLARIFY_PURCHASE_AMOUNT"),
    purposeQuote: z.string().max(160).nullable(),
    timing: timingSchema.nullable()
  }).strict(),
  z.object({
    kind: z.literal("CLARIFY_PURCHASE_MONTH"),
    amount: amountInterpretationSchema,
    purposeQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({
    kind: z.literal("CLARIFY_SCENARIO_REFERENCE"),
    attemptedOperation: z.discriminatedUnion("kind", [
      z.object({ kind: z.literal("CHANGE_PURCHASE_AMOUNT"), amount: amountInterpretationSchema }).strict(),
      z.object({ kind: z.literal("CHANGE_PURCHASE_MONTH"), timing: timingSchema }).strict(),
      z.object({ kind: z.literal("EXPLAIN_SELECTED_RESULT"), explanationTarget: z.enum(EXPLANATION_TARGET_IDS), goalReferenceQuote: z.string().max(160).nullable() }).strict(),
      z.object({ kind: z.literal("SELECT_EXISTING_SCENARIO") }).strict()
    ])
  }).strict(),
  z.object({ kind: z.literal("HELP") }).strict(),
  z.object({ kind: z.literal("GREETING") }).strict(),
  z.object({
    kind: z.literal("UNSUPPORTED"),
    category: z.enum(UNSUPPORTED_CATEGORY_IDS)
  }).strict(),
  z.object({
    kind: z.literal("AMBIGUOUS"),
    ambiguity: z.enum(AMBIGUITY_IDS)
  }).strict()
  ]).superRefine((value, context) => {
  if ("amount" in value && value.amount.currency !== "GBP") {
    context.addIssue({ code: "custom", message: "Supported purchase branches require GBP." });
  }
  if ("scenarioReferenceStrategy" in value) {
    const explicit = value.scenarioReferenceStrategy === "EXPLICIT_SCENARIO_LABEL";
    if (explicit !== (value.scenarioReferenceQuote !== null)) {
      context.addIssue({ code: "custom", message: "Scenario reference strategy and quote do not agree." });
    }
  }
  if (value.kind === "SELECT_EXISTING_SCENARIO") {
    const explicit = value.selectionTarget === "EXPLICIT_SCENARIO_LABEL";
    if (explicit !== (value.scenarioLabelQuote !== null)) {
      context.addIssue({ code: "custom", message: "Selection target and label quote do not agree." });
    }
  }
  });
}

export const conversationInterpretationSchema = buildConversationInterpretationSchema(
  completeTimingInterpretationSchema
) as z.ZodType<ConversationInterpretation>;

/** Frozen v2 branch contract retained for C1D evidence and historical replay tests. */
export const conversationInterpretationSchemaV2 = buildConversationInterpretationSchema(
  completeTimingInterpretationSchemaV2
) as z.ZodType<ConversationInterpretation>;

export const conversationInterpretationEnvelopeV2Schema = z.object({
  interpretation: conversationInterpretationSchemaV2
}).strict();

export const conversationInterpretationEnvelopeV3Schema = z.object({
  interpretation: conversationInterpretationSchema
}).strict();

/** Active v4 envelope. Its strict JSON shape remains v3-compatible; v4 adds server semantic precedence. */
export const conversationInterpretationEnvelopeV4Schema = z.object({
  interpretation: conversationInterpretationSchema
}).strict();

export const amountClarificationResolutionSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("RESOLVE_PURCHASE_AMOUNT"), amount: amountInterpretationSchema }).strict(),
  z.object({ kind: z.literal("UNSUPPORTED"), category: z.enum(UNSUPPORTED_CATEGORY_IDS) }).strict(),
  z.object({ kind: z.literal("AMBIGUOUS"), ambiguity: z.enum(AMBIGUITY_IDS) }).strict()
]);

export const monthClarificationResolutionSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("RESOLVE_PURCHASE_MONTH"), timing: completeTimingInterpretationSchema }).strict(),
  z.object({ kind: z.literal("UNSUPPORTED"), category: z.enum(UNSUPPORTED_CATEGORY_IDS) }).strict(),
  z.object({ kind: z.literal("AMBIGUOUS"), ambiguity: z.enum(AMBIGUITY_IDS) }).strict()
]);

/** Frozen v1 month-clarification contract retained for C1D comparison. */
export const monthClarificationResolutionSchemaV1 = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("RESOLVE_PURCHASE_MONTH"), timing: completeTimingInterpretationSchemaV2 }).strict(),
  z.object({ kind: z.literal("UNSUPPORTED"), category: z.enum(UNSUPPORTED_CATEGORY_IDS) }).strict(),
  z.object({ kind: z.literal("AMBIGUOUS"), ambiguity: z.enum(AMBIGUITY_IDS) }).strict()
]);

export const scenarioClarificationResolutionSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("RESOLVE_SCENARIO_REFERENCE"),
    selectionTarget: z.enum(SCENARIO_SELECTION_TARGET_IDS),
    scenarioLabelQuote: z.string().max(160).nullable()
  }).strict(),
  z.object({ kind: z.literal("UNSUPPORTED"), category: z.enum(UNSUPPORTED_CATEGORY_IDS) }).strict(),
  z.object({ kind: z.literal("AMBIGUOUS"), ambiguity: z.enum(AMBIGUITY_IDS) }).strict()
]).superRefine((value, context) => {
  if (value.kind !== "RESOLVE_SCENARIO_REFERENCE") return;
  const explicit = value.selectionTarget === "EXPLICIT_SCENARIO_LABEL";
  if (explicit !== (value.scenarioLabelQuote !== null)) {
    context.addIssue({ code: "custom", message: "Selection target and label quote do not agree." });
  }
});

export const clarificationResolutionEnvelopeSchema = z.object({
  resolution: z.union([
    amountClarificationResolutionSchema,
    monthClarificationResolutionSchema,
    scenarioClarificationResolutionSchema
  ])
}).strict();

/** Frozen v1 runtime schema retained for historical C0 evidence. */
export const conversationInterpretationV1Schema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("CREATE_ONE_OFF_PURCHASE"), amount: z.object({ quote: z.string().nullable(), currency: z.enum(["GBP", "UNSUPPORTED"]).nullable() }).strict(), timing: legacyTimingInterpretationSchema, purposeQuote: z.string().nullable(), missingFields: z.array(z.string()), unsupportedFeatures: z.array(z.string()) }).strict(),
  z.object({ kind: z.literal("CHANGE_PURCHASE_AMOUNT"), amount: z.object({ quote: z.string().nullable(), currency: z.enum(["GBP", "UNSUPPORTED"]).nullable() }).strict(), referencedScenarioLabel: z.string().nullable(), missingFields: z.array(z.string()), unsupportedFeatures: z.array(z.string()) }).strict(),
  z.object({ kind: z.literal("CHANGE_PURCHASE_MONTH"), timing: legacyTimingInterpretationSchema, referencedScenarioLabel: z.string().nullable(), missingFields: z.array(z.string()), unsupportedFeatures: z.array(z.string()) }).strict(),
  z.object({ kind: z.literal("EXPLAIN_SELECTED_RESULT"), explanationTarget: z.enum(["OVERALL_CLASSIFICATION", "SAFETY_BUFFER", "BUFFER_RECOVERY", "GOAL_DELAY", "BILLS", "BORROWING", "ASSUMPTIONS", "OTHER"]), goalReferenceQuote: z.string().nullable() }).strict(),
  z.object({ kind: z.literal("SELECT_EXISTING_SCENARIO"), scenarioReferenceQuote: z.string().nullable() }).strict(),
  z.object({ kind: z.literal("HELP") }).strict(),
  z.object({ kind: z.literal("GREETING") }).strict(),
  z.object({ kind: z.literal("UNSUPPORTED"), category: z.string(), userGoalSummary: z.string().nullable() }).strict(),
  z.object({ kind: z.literal("AMBIGUOUS"), ambiguity: z.string(), clarificationKey: z.string() }).strict()
]);

export const explanationPlanSchema = z.object({
  templateId: z.enum([
    "PURCHASE_RESULT_SIGNIFICANT", "PURCHASE_RESULT_NOTICEABLE", "PURCHASE_RESULT_MINIMAL",
    "PURCHASE_RESULT_RISKY", "BUFFER_EXPLANATION", "GOAL_DELAY_EXPLANATION",
    "TIMING_NO_IMPROVEMENT", "CURRENT_PATH_SUMMARY"
  ]),
  primaryFactKey: z.enum([
    "OVERALL_CLASSIFICATION", "BUFFER_REDUCTION", "BILLS_COVERED", "NO_BORROWING",
    "BUFFER_RECOVERY", "GOAL_DELAY", "TIMING_NO_IMPROVEMENT", "ASSUMPTIONS", "CURRENT_PATH"
  ]),
  orderedFactKeys: z.array(z.enum([
    "OVERALL_CLASSIFICATION", "BUFFER_REDUCTION", "BILLS_COVERED", "NO_BORROWING",
    "BUFFER_RECOVERY", "GOAL_DELAY", "TIMING_NO_IMPROVEMENT", "ASSUMPTIONS", "CURRENT_PATH"
  ])).min(1).max(9),
  caveatKeys: z.array(z.enum(["ASSUMED_TIMING", "HYPOTHETICAL_ONLY", "CALENDAR_FALLBACK"])).max(3),
  followUpActionKeys: z.array(z.enum([
    "TRY_LOWER_AMOUNT", "TRY_ANOTHER_MONTH", "VIEW_ASSUMPTIONS", "VIEW_CURRENT_PATH"
  ])).max(4),
  tone: z.enum(["CLEAR", "SUPPORTIVE", "DIRECT"])
}).strict();

export const createConversationRequestSchema = z.object({
  requestId: z.string().min(3).max(80).regex(/^[A-Za-z0-9_-]+$/)
}).strict();

export const sendConversationMessageRequestSchema = z.object({
  requestId: z.string().min(3).max(80).regex(/^[A-Za-z0-9_-]+$/),
  message: z.string().trim().min(1).max(1000)
}).strict();

export const selectConversationScenarioRequestSchema = z.object({
  requestId: z.string().min(3).max(80).regex(/^[A-Za-z0-9_-]+$/),
  runId: z.string().min(3).max(160).nullable()
}).strict();
